name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    environment: pypi

    permissions:
      id-token: write
      contents: read

    steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Load Pixi
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.65.0
        cache: true
        environments: builder

    - name: Install build
      run: pixi run -e builder install-build

    - name: Build project
      run: pixi run -e builder build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        package-dir: dist
